Chartboost 8.2.0 support
ChartBoost/mopub-ios-mediation pull request #11
Opened 2020-06-26 11:56 UTC by daniel-barros

Updated to use new consent methods.

2020-07-01 12:50 UTC, cristiangsp requested changes
A little comment in the Changelog.

Also, we will require Publishers to use directly our API for CCPA right?

PS: I have also disabled the Travis build on this repo as it does not makes sense to trigger the `travis.yml` as it just fails everytime (and makes sense).

2020-07-01 12:50 UTC, cristiangsp commented on Chartboost/CHANGELOG.md
> +  * 8.0.4.0
This version should not be `8.2.0.0`?

2020-07-01 14:15 UTC, daniel-barros commented on Chartboost/CHANGELOG.md
> +  * 8.0.4.0
Yeah good catch

2020-07-01 14:16 UTC, daniel-barros commented
> A little comment in the Changelog.
> Also, we will require Publishers to use directly our API for CCPA right?
> PS: I have also disabled the Travis build on this repo as it does not makes sense to trigger the `travis.yml` as it just fails everytime (and makes sense).

Thanks for disabling that!
I think we'll do what you said about CCPA, although I'm waiting for confirmation from MoPub

2020-07-08 16:27 UTC, stosiarz reviewed
Looks good to me.

2020-07-08 21:07 UTC, gheeren approved these changes
Looks good. I think that's a pretty straight forward check.

2020-09-03 12:46 UTC, closed without merging